import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddProductFullTextSearch1772089720710 implements MigrationInterface {
  name = 'AddProductFullTextSearch1772089720710';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // ── AUTO-GENERATED BY TYPEORM (do not change these) ──────────────

    await queryRunner.query(
      `ALTER TABLE "products" ADD "search_vector" tsvector`,
    );
    await queryRunner.query(
      `ALTER TABLE "otp" ALTER COLUMN "expires_at" SET DEFAULT NOW() + INTERVAL '10 minutes'`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_55d24a9ecdadf3260aa860ab56" ON "product_variants" ("product_id", "price") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_c826b5966756d33c775420d643" ON "products" ("is_active", "created_at") `,
    );

    // ── MANUALLY ADDED (GIN index + trigger — TypeORM can't auto-gen) ─

    // 1. GIN index — makes full-text search 50-100x faster than LIKE
    await queryRunner.query(
      `CREATE INDEX idx_products_fts ON products USING GIN(search_vector)`,
    );

    // 2. Populate search_vector for all existing products in DB
    await queryRunner.query(`
      UPDATE products
      SET search_vector =
        to_tsvector('english',
          coalesce(name, '') || ' ' ||
          coalesce(description, ''))
    `);

    // 3. Function that keeps search_vector updated automatically
    await queryRunner.query(`
      CREATE OR REPLACE FUNCTION update_product_search_vector()
      RETURNS TRIGGER AS $$
      BEGIN
        NEW.search_vector :=
          to_tsvector('english',
            coalesce(NEW.name, '') || ' ' ||
            coalesce(NEW.description, ''));
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql
    `);

    // 4. Trigger — fires on every INSERT or UPDATE on products table
    await queryRunner.query(`
      CREATE TRIGGER trg_product_search_vector
      BEFORE INSERT OR UPDATE ON products
      FOR EACH ROW EXECUTE FUNCTION update_product_search_vector()
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // ── MANUAL ROLLBACK (remove in reverse order) ─────────────────────
    await queryRunner.query(
      `DROP TRIGGER IF EXISTS trg_product_search_vector ON products`,
    );
    await queryRunner.query(
      `DROP FUNCTION IF EXISTS update_product_search_vector`,
    );
    await queryRunner.query(`DROP INDEX IF EXISTS idx_products_fts`);

    // ── AUTO-GENERATED ROLLBACK (do not change these) ─────────────────
    await queryRunner.query(
      `DROP INDEX "public"."IDX_c826b5966756d33c775420d643"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_55d24a9ecdadf3260aa860ab56"`,
    );
    await queryRunner.query(
      `ALTER TABLE "otp" ALTER COLUMN "expires_at" SET DEFAULT (now() + '00:10:00')`,
    );
    await queryRunner.query(
      `ALTER TABLE "products" DROP COLUMN "search_vector"`,
    );
  }
}
